---
- name: install libselinux-python, if not, ansible will raise error
  yum: name=libselinux-python state=present

- name: copy mysql source code
  copy: src=mysql-{{ mysql.version }}.tar.gz dest=/usr/local/src

- name: copy msyql install shell
  template: src=mysqlinstall.sh.j2 dest=/usr/local/src/mysqlinstall.sh

- shell: sh mysqlinstall.sh
  args:
    chdir: /usr/local/src